import { Metadata } from 'next'
import { CategoryContent } from '@/components/category'

// Sample products data with categories (will come from database later)
const allProducts = [
  // LIPS
  {
    id: '1',
    slug: 'matte-lipstick-ruby-red',
    name: 'Matte Lipstick - Ruby Red',
    price: 599,
    comparePrice: 799,
    images: [],
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    isBestseller: true,
    category: 'lips',
    variants: [
      { id: 'v1', name: 'Ruby Red', attributes: { color: '#CC0000' } },
      { id: 'v2', name: 'Berry Pink', attributes: { color: '#E91E63' } },
    ],
  },
  {
    id: '2',
    slug: 'matte-lipstick-nude-pink',
    name: 'Matte Lipstick - Nude Pink',
    price: 599,
    comparePrice: 799,
    images: [],
    rating: 4.3,
    reviewCount: 156,
    inStock: true,
    isNew: true,
    category: 'lips',
  },
  {
    id: '3',
    slug: 'velvet-lip-gloss-berry',
    name: 'Velvet Lip Gloss - Berry Bliss',
    price: 449,
    comparePrice: 599,
    images: [],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    category: 'lips',
  },
  {
    id: '4',
    slug: 'lip-liner-deep-rose',
    name: 'Precision Lip Liner - Deep Rose',
    price: 349,
    images: [],
    rating: 4.2,
    reviewCount: 67,
    inStock: true,
    category: 'lips',
  },
  {
    id: '5',
    slug: 'liquid-lipstick-maroon',
    name: 'Liquid Matte Lipstick - Maroon Magic',
    price: 649,
    comparePrice: 899,
    images: [],
    rating: 4.6,
    reviewCount: 198,
    inStock: false,
    category: 'lips',
  },
  {
    id: '6',
    slug: 'tinted-lip-balm-pink',
    name: 'Tinted Lip Balm - Rosy Pink',
    price: 299,
    images: [],
    rating: 4.4,
    reviewCount: 312,
    inStock: true,
    isNew: true,
    category: 'lips',
  },
  {
    id: '7',
    slug: 'lip-oil-cherry',
    name: 'Hydrating Lip Oil - Cherry Bomb',
    price: 399,
    comparePrice: 499,
    images: [],
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    isBestseller: true,
    category: 'lips',
  },

  // EYES
  {
    id: '10',
    slug: 'eyeshadow-palette-nude',
    name: 'Eyeshadow Palette - Nude Essentials',
    price: 1299,
    comparePrice: 1599,
    images: [],
    rating: 4.7,
    reviewCount: 324,
    inStock: true,
    isBestseller: true,
    category: 'eyes',
  },
  {
    id: '11',
    slug: 'mascara-volume-max',
    name: 'Volume Max Mascara - Black',
    price: 449,
    comparePrice: 599,
    images: [],
    rating: 4.5,
    reviewCount: 456,
    inStock: true,
    isBestseller: true,
    category: 'eyes',
  },
  {
    id: '12',
    slug: 'eyeliner-gel-black',
    name: 'Gel Eyeliner - Intense Black',
    price: 399,
    images: [],
    rating: 4.3,
    reviewCount: 189,
    inStock: true,
    category: 'eyes',
  },
  {
    id: '13',
    slug: 'eyeshadow-palette-smoky',
    name: 'Eyeshadow Palette - Smoky Nights',
    price: 1499,
    comparePrice: 1899,
    images: [],
    rating: 4.6,
    reviewCount: 267,
    inStock: true,
    isNew: true,
    category: 'eyes',
  },
  {
    id: '14',
    slug: 'kajal-waterproof',
    name: 'Waterproof Kajal - Deep Black',
    price: 249,
    images: [],
    rating: 4.4,
    reviewCount: 534,
    inStock: true,
    category: 'eyes',
  },
  {
    id: '15',
    slug: 'eyebrow-pencil-brown',
    name: 'Eyebrow Pencil - Natural Brown',
    price: 349,
    comparePrice: 449,
    images: [],
    rating: 4.2,
    reviewCount: 178,
    inStock: true,
    category: 'eyes',
  },
  {
    id: '16',
    slug: 'false-lashes-natural',
    name: 'False Lashes - Natural Glam',
    price: 299,
    images: [],
    rating: 4.1,
    reviewCount: 89,
    inStock: false,
    category: 'eyes',
  },

  // FACE
  {
    id: '20',
    slug: 'foundation-natural-beige',
    name: 'Foundation - Natural Beige',
    price: 999,
    comparePrice: 1299,
    images: [],
    rating: 4.5,
    reviewCount: 412,
    inStock: true,
    isBestseller: true,
    category: 'face',
  },
  {
    id: '21',
    slug: 'concealer-light',
    name: 'Full Coverage Concealer - Light',
    price: 549,
    comparePrice: 699,
    images: [],
    rating: 4.4,
    reviewCount: 287,
    inStock: true,
    category: 'face',
  },
  {
    id: '22',
    slug: 'blush-coral-pink',
    name: 'Powder Blush - Coral Pink',
    price: 599,
    images: [],
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    isNew: true,
    category: 'face',
  },
  {
    id: '23',
    slug: 'highlighter-golden',
    name: 'Highlighter - Golden Glow',
    price: 699,
    comparePrice: 899,
    images: [],
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    isBestseller: true,
    category: 'face',
  },
  {
    id: '24',
    slug: 'setting-powder',
    name: 'Translucent Setting Powder',
    price: 649,
    images: [],
    rating: 4.3,
    reviewCount: 156,
    inStock: true,
    category: 'face',
  },
  {
    id: '25',
    slug: 'contour-kit',
    name: 'Contour & Highlight Kit',
    price: 1199,
    comparePrice: 1499,
    images: [],
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
    category: 'face',
  },
  {
    id: '26',
    slug: 'primer-hydrating',
    name: 'Hydrating Face Primer',
    price: 599,
    images: [],
    rating: 4.4,
    reviewCount: 189,
    inStock: false,
    isNew: true,
    category: 'face',
  },

  // SKINCARE
  {
    id: '30',
    slug: 'vitamin-c-serum',
    name: 'Vitamin C Brightening Serum',
    price: 899,
    comparePrice: 1199,
    images: [],
    rating: 4.8,
    reviewCount: 567,
    inStock: true,
    isBestseller: true,
    category: 'skincare',
  },
  {
    id: '31',
    slug: 'moisturizer-hydrating',
    name: 'Deep Hydrating Moisturizer',
    price: 699,
    images: [],
    rating: 4.5,
    reviewCount: 423,
    inStock: true,
    category: 'skincare',
  },
  {
    id: '32',
    slug: 'face-wash-gentle',
    name: 'Gentle Foaming Face Wash',
    price: 399,
    comparePrice: 499,
    images: [],
    rating: 4.4,
    reviewCount: 356,
    inStock: true,
    category: 'skincare',
  },
  {
    id: '33',
    slug: 'sunscreen-spf50',
    name: 'Sunscreen SPF 50+ PA+++',
    price: 549,
    images: [],
    rating: 4.6,
    reviewCount: 478,
    inStock: true,
    isBestseller: true,
    category: 'skincare',
  },
  {
    id: '34',
    slug: 'niacinamide-serum',
    name: 'Niacinamide 10% Serum',
    price: 799,
    comparePrice: 999,
    images: [],
    rating: 4.7,
    reviewCount: 312,
    inStock: true,
    isNew: true,
    category: 'skincare',
  },
  {
    id: '35',
    slug: 'clay-mask',
    name: 'Purifying Clay Face Mask',
    price: 449,
    images: [],
    rating: 4.3,
    reviewCount: 187,
    inStock: true,
    category: 'skincare',
  },

  // NAILS
  {
    id: '40',
    slug: 'nail-polish-red',
    name: 'Nail Polish - Classic Red',
    price: 199,
    images: [],
    rating: 4.4,
    reviewCount: 234,
    inStock: true,
    isBestseller: true,
    category: 'nails',
  },
  {
    id: '41',
    slug: 'nail-polish-nude',
    name: 'Nail Polish - Nude Pink',
    price: 199,
    images: [],
    rating: 4.3,
    reviewCount: 189,
    inStock: true,
    category: 'nails',
  },
  {
    id: '42',
    slug: 'nail-polish-glitter',
    name: 'Nail Polish - Gold Glitter',
    price: 249,
    images: [],
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    isNew: true,
    category: 'nails',
  },
  {
    id: '43',
    slug: 'nail-top-coat',
    name: 'Glossy Top Coat',
    price: 179,
    images: [],
    rating: 4.2,
    reviewCount: 134,
    inStock: true,
    category: 'nails',
  },
  {
    id: '44',
    slug: 'nail-care-kit',
    name: 'Nail Care Essentials Kit',
    price: 499,
    comparePrice: 699,
    images: [],
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    category: 'nails',
  },
  {
    id: '45',
    slug: 'cuticle-oil',
    name: 'Nourishing Cuticle Oil',
    price: 249,
    images: [],
    rating: 4.4,
    reviewCount: 87,
    inStock: false,
    category: 'nails',
  },

  // COMBOS
  {
    id: '50',
    slug: 'lip-essentials-kit',
    name: 'Lip Essentials Kit',
    price: 999,
    comparePrice: 1499,
    images: [],
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    isBestseller: true,
    category: 'combos',
  },
  {
    id: '51',
    slug: 'bridal-makeup-kit',
    name: 'Bridal Makeup Collection',
    price: 4999,
    comparePrice: 6999,
    images: [],
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    category: 'combos',
  },
  {
    id: '52',
    slug: 'everyday-essentials',
    name: 'Everyday Makeup Essentials',
    price: 1999,
    comparePrice: 2799,
    images: [],
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
    isNew: true,
    category: 'combos',
  },
  {
    id: '53',
    slug: 'skincare-starter-kit',
    name: 'Skincare Starter Kit',
    price: 1499,
    comparePrice: 1999,
    images: [],
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    category: 'combos',
  },
]

const categoryInfo: Record<string, { name: string; description: string }> = {
  lips: {
    name: 'Lips',
    description: 'Discover our range of lipsticks, glosses, and lip care products',
  },
  eyes: {
    name: 'Eyes',
    description: 'Eyeshadows, mascaras, eyeliners for stunning eye makeup',
  },
  face: {
    name: 'Face',
    description: 'Foundations, concealers, blushes for a flawless complexion',
  },
  skincare: {
    name: 'Skincare',
    description: 'Cleansers, moisturizers, and serums for healthy skin',
  },
  nails: {
    name: 'Nails',
    description: 'Nail polishes, nail art, and nail care essentials',
  },
  combos: {
    name: 'Combos & Kits',
    description: 'Value sets and gift boxes for every occasion',
  },
  'new-arrivals': {
    name: 'New Arrivals',
    description: 'Check out our latest products and collections',
  },
  bestsellers: {
    name: 'Bestsellers',
    description: 'Our most loved products by customers',
  },
  all: {
    name: 'All Products',
    description: 'Browse our complete collection of beauty products',
  },
}

interface PageProps {
  params: { slug: string }
  searchParams: { [key: string]: string | string[] | undefined }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const category = categoryInfo[params.slug] || categoryInfo.all
  return {
    title: `${category.name} | Graphh Cosmetics`,
    description: category.description,
  }
}

export default function CategoryPage({ params, searchParams }: PageProps) {
  const categorySlug = params.slug
  const category = categoryInfo[categorySlug] || categoryInfo.all
  
  // Filter products by category
  let products = allProducts

  if (categorySlug === 'new-arrivals') {
    // Show only new products
    products = allProducts.filter(p => p.isNew)
  } else if (categorySlug === 'bestsellers') {
    // Show only bestsellers
    products = allProducts.filter(p => p.isBestseller)
  } else if (categorySlug !== 'all' && categoryInfo[categorySlug]) {
    // Filter by specific category
    products = allProducts.filter(p => p.category === categorySlug)
  }
  // 'all' shows everything

  return <CategoryContent category={category} products={products} />
}
